version: "3.8"

services:
  guppy:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node
    ports:
      - 3000:3000
    volumes:
      - ../..:/workspaces:cached
    networks:
      - guppy-network
      - umami-network
    command: sleep infinity

  guppy-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - guppy-network

  umami:
    image: docker.umami.is/umami-software/umami:postgresql-latest
    ports:
    - 4000:3000
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: xL1bbekT13g7aLN5jGzCWIZXZmpKsM/sMnIzinqQACE=
    depends_on:
      - umami-db
    networks:
      - guppy-network
      - umami-network
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  umami-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-data:/var/lib/postgresql/data
    networks:
      - umami-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - guppy-network
      - umami-network

volumes:
  postgres-data:
  umami-data:

networks:
  guppy-network:
    driver: bridge
  umami-network:
    driver: bridge
