name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "drizzle/**"
      - "public/**"
      - "Dockerfile"
      - "Dockerfile.migrations"
      - "package.json"
      - "pnpm-lock.yaml"
      - "next.config.ts"
      - "tsconfig.json"
      - "drizzle.config.ts"
      - "postcss.config.mjs"
      - "components.json"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
      image-labels: ${{ steps.meta.outputs.labels }}
      migration-tags: ${{ steps.meta-migrations.outputs.tags }}
      migration-labels: ${{ steps.meta-migrations.outputs.labels }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=sha-,format=long
            type=raw,value=latest

      - name: Extract metadata for Migration Docker
        id: meta-migrations
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-migrations
          tags: |
            type=sha,prefix=sha-,format=long
            type=raw,value=latest

  build-migration-image:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Migration Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.migrations
          push: true
          tags: ${{ needs.prepare.outputs.migration-tags }}
          labels: ${{ needs.prepare.outputs.migration-labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-app-image:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ needs.prepare.outputs.image-tags }}
          labels: ${{ needs.prepare.outputs.image-labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
